"""default users to user role

Revision ID: 18fd6ff2481a
Revises: a894c97f8407
Create Date: 2025-08-12 17:38:08.567033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18fd6ff2481a"
down_revision: Union[str, Sequence[str], None] = "a894c97f8407"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN role_id SET DEFAULT 5;")
    # Optionally update existing rows that have NULL
    op.execute("UPDATE users SET role_id = 5 WHERE role_id IS NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN role_id DROP DEFAULT;")
    # ### end Alembic commands ###
