"""default users to user role

Revision ID: 3ceeb65a19e8
Revises: c6676dc62f06
Create Date: 2025-08-12 17:28:33.414999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ceeb65a19e8"
down_revision: Union[str, Sequence[str], None] = "c6676dc62f06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role_id",
        server_default=sa.text("5"),
        existing_type=sa.Integer(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role_id",
        server_default=None,
        existing_type=sa.Integer(),
        nullable=False,
    )
    # ### end Alembic commands ###
